# Используется для проверки статистики администратором
POST http://127.0.0.1:8989/stats/ HTTP/1.1
Content-Type: "application/json"

{
    "admin_login": "admin",
    "admin_password_hash": "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
}